import Head from 'next/head'
import Image from 'next/image'
import Search from '../components/Search'

export default function Home({results}) {
  return (
    <div>
      <Head>
        <title>Naijakids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Search results={results}/>
    </div>
  )
}

export async function getServerSideProps(context) {
  const results = await fetch(`http://bit.ly/TeaserTask`).then((res) => res.json());
  return {
    props: {
      results
    }
  }

} 
